Adding a section on estimators
poldracklab/fitlins pull request #375
Opened 2022-06-16 13:23 UTC by Shotgunosine

2022-06-16 13:23 UTC, pep8speaks commented
Hello @Shotgunosine, thank you for submitting the Pull Request!



* In the file [`fitlins/cli/run.py`](https://github.com/poldracklab/fitlins/blob/e42ab9dd78489d9533eefde3baad3a54ab627838/fitlins/cli/run.py):

> [Line 238:41](https://github.com/poldracklab/fitlins/blob/e42ab9dd78489d9533eefde3baad3a54ab627838/fitlins/cli/run.py#L238): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

To test for issues locally, `pip install flake8` and then run `flake8 fitlins`.

2022-07-19 17:15 UTC, adelavega requested changes
Good addition! Some comments

2022-07-19 17:15 UTC, adelavega commented on docs/estimators.rst
> +In both cases, the design matrix is generated by Nilearn.
Well, I would be more specific and say it's generated by pybids + nilearn. pybids really does most of the work in design matrix generation actually.

2022-07-19 17:15 UTC, adelavega commented on docs/estimators.rst
> +Fitlins supports two estimators for first level models,
We should also explicitly mention that Nilearn is the only option for higher-level models

2022-07-22 20:02 UTC, effigies commented on docs/conf.py
> +    'afni': ('https://afni.nimh.nih.gov/pub/dist/doc/htmldoc/', None)
Huh. That's really cool.

2022-07-22 20:29 UTC, effigies commented on docs/estimators.rst
> +Fitlins supports two estimators for first level models,
Done in my changes.

2022-07-22 20:54 UTC, effigies commented
@Shotgunosine @adelavega What do you think? I'm not worried about the failing test. Seems one-off and other branches are passing.

Rendered version at https://fitlins--375.org.readthedocs.build/en/375/estimators.html

2022-07-28 17:01 UTC, Shotgunosine commented
@effigies, looks good to me!

2022-07-28 17:05 UTC, merged

2022-07-28 17:05 UTC, effigies commented
Thanks! And thanks for the first pass on this doc.